import type { Producto } from "./tipos";

/**
 * ================================================================
 *  TUS PRODUCTOS O SERVICIOS.
 *  Cada ficha sigue la "anatomía del que vende" (ver CLAUDE.md):
 *   paraQuien  → el trabajo que resuelve (Christensen, HBR 2005)
 *   beneficio  → resultado, no característica (StoryBrand)
 *   caracteristicas → SOLO 3 que importan (Iyengar, las mermeladas)
 *   precioAntes → ancla (Ariely) · facilidades → quita el miedo al gasto
 *   bono       → la oferta apilada (Hormozi)
 *   escasez    → honesta, por tiempo o unidades (Cialdini)
 *   prueba     → prueba social (Cialdini)
 * ================================================================
 */
export const PRODUCTOS: Producto[] = [
  {
    slug: "linea-tomate-grape-4x12",
    nombre: "Línea tomate grape 4x12",
    categoria: "Líneas de empaque usadas",
    imagen: "/productos/tomate-grape-4x12.jpg",
    plano: "/planos/tomate-grape-4x12-plano.png",
    galeria: [
      "/productos/tomate-grape-4x12-detalle-1.jpg",
      "/productos/tomate-grape-4x12-detalle-2.jpg",
      "/productos/tomate-grape-4x12-detalle-3.jpg",
      "/productos/tomate-grape-4x12-detalle-4.jpg",
      "/productos/tomate-grape-4x12-detalle-5.jpg",
    ],
    paraQuien:
      "Empacadoras de tomate grape que siguen clasificando a mano o con línea limitada, y quieren capacidad industrial sin pagar precio de nueva, ni tener que maquillar su fruta en otro empaque por mal cálculo de producción.",
    beneficio:
      "Clasifica por diámetro y color automáticamente; rehabilitada con software actualizado.",
    caracteristicas: ["Marca CIU · 4 líneas x 12 salidas", "Capacidad 450 kg/línea/hora", "Software actualizado"],
    frutas: ["tomate"],
    tipoCopita: "rodillo-clip",
    clasificaPor: ["diametro", "color"],
    estatus: "disponible",
    marcaFabricante: "CIU",
    resumenTarjeta: "Capacidad 450 kg/línea/hora",
    nombreCorto: "Calibrador · 4 líneas x 12 salidas",
    pasoCopita: "Rodillo 1¼\"",
    zona: "Noroeste de México",
    verificada: true,
    precio: "$3,423,255 MXN + IVA",
    facilidades: "Pago de contado antes de embarque. No incluye instalación.",
    bono: "Te conectamos con técnico especializado para instalación.",
    destacado: true,
    fichaTecnica: [
      { etiqueta: "Paso de rodillo", valor: "1¼\"" },
      { etiqueta: "Velocidad", valor: "Hasta 25 rodillos por segundo" },
      { etiqueta: "Capacidad", valor: "450 kg/hora por línea" },
      { etiqueta: "Clasifica por", valor: "Medida, color y forma" },
      { etiqueta: "Rango de medida", valor: "15-29 mm" },
      { etiqueta: "Elevador de rodillos", valor: "0.90 x 2.50 m · Acero al carbón, contacto en acero inoxidable, pintura electrostática gris clásico, motorreductor Sumitomo 220-440V 3F con variador de velocidad" },
      { etiqueta: "Cepilladora (10 cepillos)", valor: "0.90 m de ancho x 10 cepillos @ 90 mm · Acero al carbón, pintura electrostática gris clásico, contacto en acero inoxidable, cepillos azules 4.5\" corte recto, motorreductor Sumitomo 1/2 HP con variador de velocidad. No incluye arreador ni accesorios" },
      { etiqueta: "Sistema de lavado (10 cepillos)", valor: "Para cepilladora de 0.90 m de ancho · Ramal de aspersores" },
      { etiqueta: "Charolas de escurrimiento (10 cepillos)", valor: "0.90 m de ancho x 10 cepillos · Acero inoxidable" },
      { etiqueta: "Cepilladora (25 cepillos)", valor: "0.90 m de ancho x 25 cepillos @ 90 mm · Acero al carbón, pintura electrostática gris clásico, contacto en acero inoxidable, cepillos azules 4.5\" corte recto, motorreductor Sumitomo 1½ HP con variador de velocidad. No incluye arreador ni accesorios" },
      { etiqueta: "Charolas de escurrimiento (25 cepillos)", valor: "0.90 m de ancho x 25 cepillos @ 90 mm · Acero inoxidable" },
      { etiqueta: "Sistema de raseros", valor: "Para cepilladora de 0.90 m de ancho x 25 cepillos · Acero galvanizado" },
      { etiqueta: "Ventiladores axiales", valor: "1 HP, 0.90 x 0.90 m · Acero al carbón, pintura electrostática gris clásico, incluye estructura de soporte" },
      { etiqueta: "Descanicador ajustable", valor: "Acero al carbón, pintura electrostática, motorreductor de ½ HP 220-440V" },
      { etiqueta: "Selección manual", valor: "0.90 m de ancho x 3.00 m de largo · Acero al carbón, pintura electrostática gris clásico, tubos de acero inoxidable de 2\", contacto en acero inoxidable, motorreductor Sumitomo ½ HP con variador de velocidad. No incluye accesorios" },
      { etiqueta: "Banda sanitaria inferior", valor: "12\" de ancho x 3.0 m, para selección manual · Acero inoxidable, motorreductor Sumitomo ¼ HP 220-440V, incluye bajada lateral" },
      { etiqueta: "Andamio lateral", valor: "0.60 m de ancho x 3.0 m de largo · Acero al carbón, pintura electrostática gris clásico, incluye escalón con pasamanos" },
      { etiqueta: "Cajón de recepción de fruta", valor: "0.70 x 0.70 m · Acero al carbón, pintura electrostática gris clásico, dulona azul de 6 mm" },
      { etiqueta: "Singulador de bandas en V", valor: "4 líneas x 3.05 m, para clasificadora paso 1¼\" · Acero al carbón, contacto en acero inoxidable, pintura electrostática gris clásico, motorreductor Sumitomo 2 HP con variador de velocidad" },
      { etiqueta: "Clasificadora computarizada", valor: "Paso 1¼\", 4 líneas x 12 salidas @ 22½\" · Clasifica por tamaño y color, descarga a un solo lado, acero al carbón con pintura electrostática gris clásico, contacto en acero inoxidable 441, paros de emergencia, computadora y monitor LCD 19\", electrónica y software CIU, cámaras de color de alta velocidad, sistema de retorno de fruta no clasificada, motorreductor Sumitomo 2 HP con variador de velocidad, incluye no-break. No incluye compresor" },
      { etiqueta: "Tolva de recepción", valor: "0.90 m de ancho x 12 salidas a 22.5° · Acero al carbón, pintura electrostática gris clásico, dulona de 6 mm, puerta para llenado de cajas. No incluye instalación mecánica ni eléctrica" },
    ],
    garantia: "Antes de que te la lleves, la encendemos frente a ti en la bodega: prendemos y probamos cada función para que la veas trabajar. Se vende como está — puede faltarle un detalle menor (un tornillo, una lámina, o como vaya pintada), nunca algo que afecte su funcionamiento. Tú decides viéndola encendida. No se entrega instalada, salvo que contrates la instalación aparte. Trabajamos con contrato firmado: se cubre un anticipo antes de iniciar la carga, y el resto se liquida antes de que la máquina salga del empaque.",
  },
  {
    slug: "linea-citricos",
    nombre: "Línea completa para cítricos",
    categoria: "Líneas de empaque usadas",
    imagen: "/productos/citricos.jpg",
    plano: "/planos/linea-citricos-plano.png",
    galeria: [
      "/productos/citricos-detalle-1.jpg",
      "/productos/citricos-detalle-2.jpg",
      "/productos/citricos-detalle-3.jpg",
      "/productos/citricos-detalle-4.jpg",
      "/productos/citricos-detalle-5.jpg",
      "/productos/citricos-detalle-6.jpg",
    ],
    paraQuien:
      "Empacadoras de cítricos que buscan una línea completa (selección, lavado, encerado y calibrado) en acero inoxidable, sin pagar precio de una línea nueva instalada.",
    beneficio:
      "Volteadora de bins, descanicador, 2 mesas de selección manual, 2 cepilladoras de lavado/encerado, 2 secadoras de cera (gas LP) y calibrador de tubos ajustables. Semi-nueva, con solo 1 temporada de uso.",
    caracteristicas: ["Marca SIAI · Todo en acero inoxidable", "Calibrador de tubos ajustables", "Semi-nueva · Solo 1 temporada de uso"],
    frutas: ["cítricos"],
    clasificaPor: ["diametro"],
    estatus: "disponible",
    marcaFabricante: "SIAI",
    resumenTarjeta: "Calibrador de tubos ajustables",
    nombreCorto: "Calibrador · Cítricos",
    pasoCopita: "4 salidas 1ª + 4 de 2ª calidad · Inoxidable",
    videoYoutube: "https://youtu.be/TctLsLShK0A",
    verificada: true,
    zona: "Noroeste de México",
    precio: "$4,500,000 MXN + IVA",
    facilidades: "Pago de contado antes de embarque. Sin instalar.",
    fichaTecnica: [
      { etiqueta: "Clasifica por", valor: "Primera y segunda calidad (en las mesas de selección manual)" },
      { etiqueta: "Volteadora de bins (ancho)", valor: "51\" · 450 kg/minuto" },
      { etiqueta: "Selección manual", valor: "1.7 x 4 m" },
      { etiqueta: "Descanicador fijo", valor: "1.8 x 2.5 m" },
      { etiqueta: "Cepilladora de lavado", valor: "1.5 x 4.8 m" },
      { etiqueta: "Secado de lavado", valor: "1.5 x 4 m y 1.5 x 4.47 m" },
      { etiqueta: "Cepilladora de encerado", valor: "1.5 x 2.23 m" },
      { etiqueta: "Secado de encerado", valor: "1.5 x 7.4 m" },
      { etiqueta: "Selección manual (jugo)", valor: "1.5 x 6 m" },
      { etiqueta: "Calibrador de tubos", valor: "2 x 6.2 m · 4 salidas de primera calidad + 4 salidas de segunda calidad" },
      { etiqueta: "Bandas distribuidoras", valor: "0.92 x 16.1 m y 0.92 x 7.85 m" },
    ],
    garantia: "Antes de que te la lleves, la encendemos frente a ti en la bodega: prendemos y probamos cada función para que la veas trabajar. Se vende como está — puede faltarle un detalle menor (un tornillo, una lámina, o como vaya pintada), nunca algo que afecte su funcionamiento. Tú decides viéndola encendida. No se entrega instalada, salvo que contrates la instalación aparte. Trabajamos con contrato firmado: se cubre un anticipo antes de iniciar la carga, y el resto se liquida antes de que la máquina salga del empaque.",
  },
  {
    slug: "clasificadora-6-lineas",
    nombre: "Clasificadora 6 líneas x 12 salidas (mango, chile morrón, aguacate)",
    categoria: "Líneas de empaque usadas",
    imagen: "/productos/clasificadora-6-lineas.jpg",
    plano: "/planos/clasificadora-6-lineas-plano.png",
    galeria: [
      "/productos/clasificadora-6-lineas-detalle-1.jpg",
      "/productos/clasificadora-6-lineas-detalle-2.jpg",
      "/productos/clasificadora-6-lineas-detalle-3.jpg",
      "/productos/clasificadora-6-lineas-detalle-4.jpg",
      "/productos/clasificadora-6-lineas-detalle-5.jpg",
      "/productos/clasificadora-6-lineas-detalle-6.jpg",
    ],
    paraQuien:
      "Empacadoras de mango, chile morrón o aguacate que clasifican a mano y quieren pasar a clasificación automática por peso, sin pagar precio de una nueva.",
    beneficio:
      "Clasifica por peso con singulador de cepillos; motor, cadenas, cableado y sistema de pesaje nuevos.",
    caracteristicas: ["Marca CIU · 6 líneas x 12 salidas x 1 de error", "Capacidad 1.9 ton/línea por hora", "Pintura electrostática nueva (gris)"],
    frutas: ["mango", "chile morrón", "aguacate"],
    tipoCopita: "charola",
    clasificaPor: ["peso"],
    estatus: "disponible",
    marcaFabricante: "CIU",
    resumenTarjeta: "Capacidad 1.9 ton/línea por hora",
    nombreCorto: "Calibrador · 6 líneas x 12 salidas",
    pasoCopita: "Charola 6\"",
    videoYoutube: "https://youtube.com/shorts/n_vXUN2YyXk",
    verificada: true,
    zona: "Noroeste de México",
    precio: "$1,500,000 MXN",
    facilidades: "Pago de contado antes de embarque. Sin instalación.",
    bono: "Incluye caseta de vigilancia.",
    fichaTecnica: [
      { etiqueta: "Tipo", valor: "Clasificadora de charolas paso 6\", 6 líneas x 12+1 salidas @ 30\"" },
      { etiqueta: "Acabado", valor: "Pintura electrostática nueva, color gris" },
      { etiqueta: "Velocidad", valor: "3 charolas por segundo" },
      { etiqueta: "Capacidad", valor: "1.9 ton/línea por hora (fruta de 300 g)" },
      { etiqueta: "Clasifica por", valor: "Peso" },
      { etiqueta: "Rango de medida", valor: "85-150 mm" },
      { etiqueta: "Singulador de cepillos", valor: "6 líneas x 3.05 m de longitud, para charolas @ 7.5\" · Acero al carbón, pintura electrostática, contacto en acero inoxidable" },
      { etiqueta: "Clasificadora computarizada", valor: "Descarga hacia ambos lados · Acero al carbón con pintura electrostática, contacto en acero inoxidable, paros de emergencia en ubicaciones estratégicas, computadora y monitor LCD 19\", electrónica y software CIU, sistema de protección a cortes de energía (no-break), motor trifásico 220-440V, incluye mesa de control. No incluye instalación eléctrica ni mecánica" },
    ],
    garantia: "Antes de que te la lleves, la encendemos frente a ti en la bodega: prendemos y probamos cada función para que la veas trabajar. Se vende como está — puede faltarle un detalle menor (un tornillo, una lámina, o como vaya pintada), nunca algo que afecte su funcionamiento. Tú decides viéndola encendida. No se entrega instalada, salvo que contrates la instalación aparte. Trabajamos con contrato firmado: se cubre un anticipo antes de iniciar la carga, y el resto se liquida antes de que la máquina salga del empaque.",
  },
  {
    slug: "linea-tomate-roma-bola",
    nombre: "Línea tomate roma / bola — Clasificadora 2 líneas x 12 salidas",
    categoria: "Líneas de empaque usadas",
    plano: "/planos/tomate-roma-bola-plano.png",
    imagen: "/productos/tomate-roma-bola.jpg",
    galeria: [
      "/productos/tomate-roma-bola-detalle-1.jpg",
      "/productos/tomate-roma-bola-detalle-2.jpg",
      "/productos/tomate-roma-bola-detalle-3.jpg",
      "/productos/tomate-roma-bola-detalle-4.jpg",
      "/productos/tomate-roma-bola-detalle-5.jpg",
      "/productos/tomate-roma-bola-detalle-6.jpg",
    ],
    paraQuien:
      "Empacadoras de tomate roma o bola que necesitan clasificar por tamaño y color con capacidad de expansión, sin comprar una línea nueva.",
    beneficio:
      "Clasifica por tamaño y color; incluye singulador, cepilladora, elevador con base para caja llena y bancos para cajas ya empacadas.",
    caracteristicas: ["Marca CIU · 2 líneas x 12 salidas (expandible)", "Capacidad 7.2 ton/línea", "Incluye elevador y bancos de descanso"],
    frutas: ["tomate"],
    tipoCopita: "rodillo-clip",
    clasificaPor: ["diametro", "color"],
    estatus: "disponible",
    marcaFabricante: "CIU",
    resumenTarjeta: "Capacidad 7.2 ton/línea",
    nombreCorto: "Calibrador · 2 líneas x 12 salidas",
    pasoCopita: "Rodillo 3¾\"",
    videoYoutube: "https://youtube.com/shorts/M8GI_vTX3qc",
    verificada: true,
    zona: "Centro de México",
    precio: "$1,300,000 MXN",
    facilidades: "Pago de contado antes de embarque. No incluye instalación.",
    fichaTecnica: [
      { etiqueta: "Paso de rodillo", valor: "3¾\" (sin peso)" },
      { etiqueta: "Velocidad", valor: "Hasta 12 rodillos por segundo" },
      { etiqueta: "Capacidad", valor: "~7.2 ton/hora por línea (ajustado a fruta de 280 g, 60% de llenado)" },
      { etiqueta: "Clasifica por", valor: "Medida, color y forma" },
      { etiqueta: "Rango de medida", valor: "54-86 mm" },
      { etiqueta: "Salidas de fábrica", valor: "2 líneas x 7 salidas, ampliada a 12 (modelo económico)" },
      { etiqueta: "Elevador de rodillos", valor: "0.60 x 3.0 m" },
      { etiqueta: "Andamio lateral", valor: "0.60 x 3.0 m" },
      { etiqueta: "Cepilladora", valor: "0.60 m, 10 cepillos" },
      { etiqueta: "Banda transportadora a clasificadora", valor: "16\" x 2.0 m" },
      { etiqueta: "Singulador de bandas en V", valor: "2L x 3.0 m" },
      { etiqueta: "Tolva de recepción", valor: "1.20 m de ancho, 12 salidas a 22.5°" },
      { etiqueta: "Banco para llenado de caja", valor: "0.30 x 0.45 m (x12)" },
    ],
    garantia: "Antes de que te la lleves, la encendemos frente a ti en la bodega: prendemos y probamos cada función para que la veas trabajar. Se vende como está — puede faltarle un detalle menor (un tornillo, una lámina, o como vaya pintada), nunca algo que afecte su funcionamiento. Tú decides viéndola encendida. No se entrega instalada, salvo que contrates la instalación aparte. Trabajamos con contrato firmado: se cubre un anticipo antes de iniciar la carga, y el resto se liquida antes de que la máquina salga del empaque.",
  },
  {
    slug: "clasificadora-4x12-morron-mango-aguacate",
    nombre: "Clasificadora morrón, mango, cebolla y aguacate — 4 líneas x 12 salidas",
    categoria: "Líneas de empaque usadas",
    imagen: "/productos/clasificadora-4x12-morron-12.jpg",
    galeria: [
      "/productos/clasificadora-4x12-morron-1.jpg",
      "/productos/clasificadora-4x12-morron-3.jpg",
      "/productos/clasificadora-4x12-morron-7.jpg",
      "/productos/clasificadora-4x12-morron-6.jpg",
      "/productos/clasificadora-4x12-morron-11.jpg",
      "/productos/clasificadora-4x12-morron-8.jpg",
      "/productos/clasificadora-4x12-morron-9.jpg",
      "/productos/clasificadora-4x12-morron-4.jpg",
      "/productos/clasificadora-4x12-morron-2.jpg",
      "/productos/clasificadora-4x12-morron-5.jpg",
      "/productos/clasificadora-4x12-morron-10.jpg",
    ],
    paraQuien:
      "Empacadoras de chile morrón, mango, cebolla o aguacate que clasifican a mano y quieren pasar a clasificación automática por peso, sin pagar precio de una nueva.",
    beneficio:
      "Clasifica por peso; incluye elevador con mesa de selección manual (para sacar segunda calidad), 2 bandas de bajada para dirigir la fruta a un bin, básculas, transportadores de caja vacía y llena, y caseta de vigilancia.",
    caracteristicas: ["Marca CIU · 4 líneas x 12 salidas", "Semi-nueva · Solo 1 temporada de uso", "Incluye caseta de vigilancia"],
    frutas: ["chile morrón", "mango", "cebolla", "aguacate"],
    tipoCopita: "rodillo-clip",
    clasificaPor: ["peso"],
    estatus: "disponible",
    videoYoutube: "https://youtu.be/tNgklxIraIc",
    marcaFabricante: "CIU",
    resumenTarjeta: "Semi-nueva · 1 temporada de uso",
    nombreCorto: "Calibrador · 4 líneas x 12 salidas",
    pasoCopita: "Rodillo 4½\" (con peso)",
    verificada: true,
    zona: "Noroeste de México",
    precio: "$3,500,000 MXN",
    facilidades: "Pago de contado antes de embarque. No incluye instalación.",
    fichaTecnica: [
      { etiqueta: "Paso de rodillo", valor: "4½\" (con peso)" },
      { etiqueta: "Velocidad", valor: "Hasta 9 rodillos por segundo" },
      { etiqueta: "Capacidad", valor: "8 ton/hora por línea (peso promedio 400 g por fruta)" },
      { etiqueta: "Clasifica por", valor: "Solo peso (sin cámaras: no clasifica color, defecto ni forma)" },
      { etiqueta: "Rango de medida", valor: "58-103 mm" },
      { etiqueta: "Mesa de selección manual", valor: "1.20 m de ancho x 3 m de largo, tipo elevador · Banda superior de canjilones, banda sanitaria desviadora con guías al centro: primera calidad va directo a la clasificadora, segunda calidad se aparta" },
      { etiqueta: "Singulador de bandas en V", valor: "4 líneas, alimenta la clasificadora" },
      { etiqueta: "Bandas de bajada (segunda calidad)", valor: "2 bandas con canjilones, ~4 m de largo (una de 1 pie de ancho, otra de 2 pies de ancho) · Contacto con la fruta en acero inoxidable, banda de PVC, canjilones de PVC o Nylamide. Bajan la segunda calidad de la mesa de selección hacia la segunda selección. No incluye la banda larga donde se selecciona la segunda calidad a mano" },
      { etiqueta: "Caseta de vigilancia", valor: "Incluida" },
    ],
    garantia: "Antes de que te la lleves, la encendemos frente a ti en la bodega: prendemos y probamos cada función para que la veas trabajar. Se vende como está — puede faltarle un detalle menor (un tornillo, una lámina, o como vaya pintada), nunca algo que afecte su funcionamiento. Tú decides viéndola encendida. No se entrega instalada, salvo que contrates la instalación aparte. Trabajamos con contrato firmado: se cubre un anticipo antes de iniciar la carga, y el resto se liquida antes de que la máquina salga del empaque.",
  },
  {
    slug: "volteadora-bins-rochin",
    nombre: "Volteadora de bins Rochin",
    categoria: "Líneas de empaque usadas",
    imagen: "/productos/volteadora-bins-rochin-4.jpg",
    galeria: [
      "/productos/volteadora-bins-rochin-2.jpg",
      "/productos/volteadora-bins-rochin-5.jpg",
      "/productos/volteadora-bins-rochin-1.jpg",
      "/productos/volteadora-bins-rochin-3.jpg",
      "/productos/volteadora-bins-rochin-6.jpg",
      "/productos/volteadora-bins-rochin-7.jpg",
    ],
    paraQuien:
      "Empacadoras que todavía usan taras en campo y quieren dar el salto a bins: esta es tu oportunidad de dejar las taras, sin contar cubeta por cubeta y con un llenado de la línea de empaque más parejo.",
    beneficio:
      "Voltea bins llenos de forma automática y continua, toda en acero inoxidable: mientras uno se vacía en el tambor circular, hasta 3 más esperan en fila por sensor, y los bins vacíos salen por un transportador de rodillos de gravedad.",
    caracteristicas: ["Marca Rochin · Nueva, nunca usada", "Todo en acero inoxidable", "Programación remota, sin necesidad de técnico en planta"],
    frutas: ["tomate", "pepino", "chile morrón", "chile jalapeño", "chile rojo"],
    estatus: "disponible",
    marcaFabricante: "Rochin",
    resumenTarjeta: "Todo en acero inoxidable",
    nombreCorto: "Volteadora de bins",
    videoYoutube: "https://youtube.com/shorts/GTJHDDYohWo",
    zona: "Noroeste de México",
    precio: "$2,300,000 MXN",
    fichaTecnica: [
      { etiqueta: "Marca", valor: "Rochin" },
      { etiqueta: "Condición", valor: "Nueva, nunca usada" },
      { etiqueta: "Material", valor: "Toda la máquina en acero inoxidable" },
      { etiqueta: "Mecanismo", valor: "Volteo circular · Entrada por cadena con sensor, salida por gravedad" },
      { etiqueta: "Programación", valor: "Remota, sin necesidad de que el técnico esté físicamente en la planta — útil en caso de apagón o crisis operativa durante temporada" },
      { etiqueta: "Capacidad de rieles", valor: "3 bins llenos en espera (cadena + sensor) + 1 volteando + 3 bins vacíos en espera de salida (transportador de rodillos de gravedad, tubo inoxidable)" },
      { etiqueta: "Rendimiento", valor: "2 bins por minuto" },
      { etiqueta: "Requiere", valor: "Montacargas para cargar y descargar los bins" },
      { etiqueta: "Banda de salida (producto)", valor: "Azul de PVC, 1.20 m de ancho x 1.50 m de largo, 1.20 m de alto del piso a la flecha" },
      { etiqueta: "Bin compatible", valor: "1.20 x 1.20 m, 21½\" de alto · 544.3 litros de volumen interior" },
      { etiqueta: "Tamaño de fruta", valor: "Cualquier producto (jitomate, pepino, morrón, jalapeño, chile, etc.) de tamaño pepino o más chico. Al ser un bin chico, la fruta de abajo no se aplasta con el peso de la de arriba" },
      { etiqueta: "Dimensiones generales", valor: "8 m de largo x 3.70 m de ancho x 11 pies de alto (~3.35 m)" },
      { etiqueta: "Tablero eléctrico", valor: "Nuevo, con PLC y variadores Siemens" },
    ],
    garantia: "Antes de que te la lleves, la encendemos frente a ti en la bodega: prendemos y probamos cada función para que la veas trabajar. Se vende como está — puede faltarle un detalle menor (un tornillo, una lámina, o como vaya pintada), nunca algo que afecte su funcionamiento. Tú decides viéndola encendida. No se entrega instalada, salvo que contrates la instalación aparte. Trabajamos con contrato firmado: se cubre un anticipo antes de iniciar la carga, y el resto se liquida antes de que la máquina salga del empaque.",
  },
  {
    slug: "clasificadora-pepino-2x7",
    nombre: "Clasificadora de pepino — 2 líneas x 7 salidas",
    categoria: "Líneas de empaque usadas",
    imagen: "/productos/clasificadora-pepino.jpg",
    plano: "/planos/clasificadora-pepino-plano.png",
    galeria: [
      "/productos/clasificadora-pepino-detalle-1.jpg",
      "/productos/clasificadora-pepino-detalle-2.jpg",
      "/productos/clasificadora-pepino-detalle-3.jpg",
      "/productos/clasificadora-pepino-detalle-4.jpg",
      "/productos/clasificadora-pepino-detalle-5.jpg",
    ],
    paraQuien:
      "Empacadoras de pepino que clasifican a mano y quieren pasar a clasificación automática por peso, medida y forma, sin pagar precio de una nueva.",
    beneficio: "Clasifica por peso, medida y forma en charola paso 6\" especial — la copita hecha para pepino.",
    caracteristicas: ["Charola paso 6\" especial · 2 líneas x 7 salidas", "Capacidad ~4.4 ton/hr (2.2 ton/hr por línea)", "Clasifica por peso, medida y forma"],
    frutas: ["pepino"],
    tipoCopita: "charola",
    clasificaPor: ["peso", "diametro"],
    estatus: "disponible",
    marcaFabricante: "CIU",
    resumenTarjeta: "Capacidad ~4.4 ton/hr",
    nombreCorto: "Calibrador · 2 líneas x 7 salidas",
    pasoCopita: "Charola 6\" especial",
    precio: "Precio a consultar",
    facilidades: "Pago de contado antes de embarque. No incluye instalación.",
    fichaTecnica: [
      { etiqueta: "Tipo", valor: "Clasificadora de charolas, paso 6\" especial" },
      { etiqueta: "Presentación", valor: "Se vende en 2 piezas de máquina (no es una sola línea integrada)" },
      { etiqueta: "Configuración", valor: "2 líneas x 7 salidas" },
      { etiqueta: "Velocidad", valor: "Hasta 4.5 charolas por segundo" },
      { etiqueta: "Capacidad", valor: "2.2 ton/hr por línea (fruta de 200 g prom.)" },
      { etiqueta: "Clasifica por", valor: "Peso, medida y forma" },
      { etiqueta: "Rango de medida", valor: "100-280 mm" },
      { etiqueta: "Fruta", valor: "Pepino" },
    ],
    garantia: "Antes de que te la lleves, la encendemos frente a ti en la bodega: prendemos y probamos cada función para que la veas trabajar. Se vende como está — puede faltarle un detalle menor (un tornillo, una lámina, o como vaya pintada), nunca algo que afecte su funcionamiento. Tú decides viéndola encendida. No se entrega instalada, salvo que contrates la instalación aparte. Trabajamos con contrato firmado: se cubre un anticipo antes de iniciar la carga, y el resto se liquida antes de que la máquina salga del empaque.",
  },
  {
    slug: "linea-tomate-roma-4x24",
    nombre: "Línea completa para tomate Roma — Clasificadora 4 líneas x 24 salidas",
    categoria: "Líneas de empaque usadas",
    imagen: "/productos/linea-tomate-roma-4x24-detalle-1.jpg",
    plano: "/planos/linea-tomate-roma-4x24-plano.png",
    galeria: [
      "/productos/linea-tomate-roma-4x24-detalle-2.jpg",
      "/productos/linea-tomate-roma-4x24-detalle-3.jpg",
      "/productos/linea-tomate-roma-4x24-detalle-4.jpg",
      "/productos/linea-tomate-roma-4x24-detalle-5.jpg",
      "/productos/linea-tomate-roma-4x24.jpg",
    ],
    paraQuien:
      "Empacadoras de tomate Roma que buscan una línea completa (selección, lavado, encerado, secado y clasificación) marca idepro, sin pagar precio de una línea nueva instalada.",
    beneficio:
      "Línea completa de principio a fin: volteadora, selección manual, descanicador, cepilladoras de lavado y encerado, secadores, clasificadora computarizada de 4 líneas x 24 salidas, tolvas, básculas y transportadores.",
    caracteristicas: ["Marca idepro · Línea completa", "Clasificadora 4 líneas x 24 salidas, clip 3¾\"", "Clasifica por tamaño y color, control por Android"],
    frutas: ["tomate"],
    tipoCopita: "rodillo-clip",
    clasificaPor: ["diametro", "color"],
    estatus: "disponible",
    marcaFabricante: "Idepro",
    resumenTarjeta: "Clasifica por tamaño y color, control por Android",
    nombreCorto: "Calibrador · 4 líneas x 24 salidas",
    pasoCopita: "Clip 3¾\"",
    videoYoutube: "https://youtube.com/shorts/QSAoBBOE6hY",
    verificada: true,
    zona: "Noroeste de México",
    precio: "Precio a consultar",
    facilidades: "Pago de contado antes de embarque. No incluye instalación.",
    fichaTecnica: [
      { etiqueta: "Volteadora lineal de cajas de campo", valor: "Incluye alimentador de cajas de 3 m y resbaladilla final" },
      { etiqueta: "Selección manual inclinada", valor: "48\" x 3.05 m · Incluye guías, bancas y cajón de rezaga" },
      { etiqueta: "Descanicador", valor: "48\" x 2.0 m" },
      { etiqueta: "Cepilladora (lavado)", valor: "48\" x 24 cepillos de 5\", con arreador y sistema de lavado por aspersión" },
      { etiqueta: "Túnel de secado (lavado)", valor: "48\" x 4.5 m, con 6 ventiladores axiales" },
      { etiqueta: "Cepilladora (encerado)", valor: "48\" x 12 cepillos de 5\", con sistema de encerado por disco rotativo" },
      { etiqueta: "Túnel de secado (encerado)", valor: "48\" x 3.05 m, con 4 ventiladores axiales" },
      { etiqueta: "Selección manual final", valor: "48\" x 3.05 m · Incluye guías, bancas y cajón de rezaga" },
      { etiqueta: "Banda de rezaga", valor: "12\" x 3.05 m" },
      { etiqueta: "Banda de retorno", valor: "8\" x 18 m · Regresa a la clasificadora la fruta mal acomodada" },
      { etiqueta: "Clasificadora computarizada", valor: "4 líneas x 24 salidas @ 15\" · Clasifica por tamaño y color, control inalámbrico por Android" },
      { etiqueta: "Capacidad de clasificación", valor: "9-11 ton/hr (fruta de 130 g prom.) · 14-16 ton/hr (fruta de 200 g prom.)" },
      { etiqueta: "Tolvas de recepción", valor: "24 piezas, 30\" x 1.20 m de fondo, con puerta deslizable" },
      { etiqueta: "Básculas", valor: "24 piezas de 100 kg, charola de 62 x 34 cm" },
      { etiqueta: "Transportador para caja llena (gravedad)", valor: "16\" de ancho" },
      { etiqueta: "Transportador de riel para caja vacía", valor: "16\" de ancho" },
    ],
    garantia: "Antes de que te la lleves, la encendemos frente a ti en la bodega: prendemos y probamos cada función para que la veas trabajar. Se vende como está — puede faltarle un detalle menor (un tornillo, una lámina, o como vaya pintada), nunca algo que afecte su funcionamiento. Tú decides viéndola encendida. No se entrega instalada, salvo que contrates la instalación aparte. Trabajamos con contrato firmado: se cubre un anticipo antes de iniciar la carga, y el resto se liquida antes de que la máquina salga del empaque.",
  },
];

/** Productos de una categoría, con el destacado primero. */
export function productosPorCategoria(categoria: string): Producto[] {
  return PRODUCTOS.filter((p) => p.categoria === categoria).sort(
    (a, b) => Number(b.destacado ?? false) - Number(a.destacado ?? false)
  );
}

/** Busca un producto por su slug (para la ficha individual). */
export function productoPorSlug(slug: string): Producto | undefined {
  return PRODUCTOS.find((p) => p.slug === slug);
}
